# ################### GLOBAL ###################

global:
  environmentName: gamma

chains:
  river:
    chainId: 6524490
    contractAddresses:
      riverRegistry: "0xf18E98D36A6bd1aDb52F776aCc191E69B491c070"

appOfApps:
  applications:
    - name: argocd
      namespace: argocd
      disable: false
    - name: datadog
      namespace: datadog
      disable: false
    - name: external-secrets
      namespace: external-secrets
      disable: false
    - name: cert-manager
      namespace: cert-manager
      disable: false
    - name: external-dns
      namespace: external-dns
      disable: false
    - name: main-alb
      namespace: default
      disable: false
    - name: xchain-monitor
      namespace: default
      disable: true
    - name: metrics-aggregator
      namespace: default
      disable: false
    - name: notification-service
      namespace: default
      disable: false
    - name: river-node
      namespace: default
      disable: false

notificationService:
  image:
    tag: 33e06b3
  apnsTownsAppIdentifier: com.towns.internal

riverNode:
  image:
    tag: dev
  numStreamNodes: 11
  numArchiveNodes: 0
