# ################### GLOBAL ###################

global:
  environmentName: gamma

chains:
  river:
    chainId: 6524490
    contractAddresses:
      riverRegistry: "0xf18E98D36A6bd1aDb52F776aCc191E69B491c070"

appOfApps:
  applications:
    - name: cert-manager
      namespace: cert-manager
      disable: true
    - name: datadog
      namespace: datadog
      disable: false
    - name: external-secrets
      namespace: external-secrets
      disable: false
    - name: metrics-aggregator
      namespace: default
      disable: false
    - name: notification-service
      namespace: default
      disable: false

notificationService:
  image:
    tag: dev
  apnsTownsAppIdentifier: com.towns.internal
