# ################### GLOBAL ###################

global:
  environmentName: gamma

chains:
  river:
    chainId: 6524490
    contractAddresses:
      riverRegistry: "0xf18E98D36A6bd1aDb52F776aCc191E69B491c070"

appOfApps:
  applications:
    - name: cert-manager
      disable: true
      namespace: cert-manager
    - name: datadog
      disable: true
      namespace: datadog
    - name: external-secrets
      disable: true
      namespace: external-secrets
    - name: metrics-aggregator
      disable: true
      namespace: default
    - name: notification-service
      disable: false
      namespace: default
