# ################### GLOBAL ###################

global:
  environmentName: omega

chains:
  river:
    chainId: "550"
    contractAddresses:
      riverRegistry: "0x1298c03Fde548dc433a452573E36A713b38A0404"
  base:
    chainId: "8453"
    contractAddresses:
      spaceArchitect: "0x9978c826d93883701522d2CA645d5436e5654252"
      baseRegistry: "0x7c0422b31401C936172C897802CF0373B35B7698"

notificationService:
  image:
    tag: "mainnet"
  resources:
    limits:
      cpu: "1.5"
      memory: "76Gi"
    requests:
      cpu: "1.5"
      memory: "76Gi"
  apnsTownsAppIdentifier: com.towns.ios # TODO: always change

riverNode:
  image:
    tag: "mainnet"
    pullPolicy: Always
  migrationStatus:
    stream:
      1: "hold"
      2: "hold"
  numStreamNodes: 2
  numArchiveNodes: 2
  apmEnabled: true
  resources:
    limits:
      cpu: "2"
      memory: "8Gi"
    requests:
      cpu: "2"
      memory: "8Gi"

argocd:
  externalAccess:
    enabled: true

appOfApps:
  applications:
    - name: argocd
      namespace: argocd
      disable: false
    - name: datadog
      namespace: datadog
      disable: false
    - name: external-secrets
      namespace: external-secrets
      disable: false
    - name: cert-manager
      namespace: cert-manager
      disable: false
    - name: external-dns
      namespace: external-dns
      disable: false
    - name: main-alb
      namespace: default
      disable: false
    - name: xchain-monitor
      namespace: default
      disable: false
    - name: metrics-aggregator
      namespace: default
      disable: false
    - name: notification-service
      namespace: default
      disable: false
    - name: river-node
      namespace: default
      disable: false
