apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: argocd-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - {{ include "argocd.domainName" . }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "argocd.fullname" . }}
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "main-alb-ip"
    kubernetes.io/ingress.class: gce
    # TODO: disallow http, only allow https
    kubernetes.io/ingress.allow-http: "true"
    external-dns.alpha.kubernetes.io/hostname: {{ include "argocd.domainName" . }}
spec:
  tls:
    - hosts:
        - {{ include "argocd.domainName" . }}
      secretName: argocd-tls
  rules:
    - host: {{ include "argocd.domainName" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 80