apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rpc-gateway-secrets
  namespace: {{ $.Release.Namespace }} 
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: upstream_url_base_alchemy
      remoteRef:
        key: rpc_gateway_upstream_urls
        property: base_alchemy
        version: latest
