# ArgoCD proxy default rate limiting configuration
argocdProxy:
  trustedProxies:
    enabled: false
    cidrBlocks:
    - 35.191.0.0/16
    - 130.211.0.0/22
    - 35.235.240.0/20
    - 209.85.152.0/22
    - 209.85.204.0/22
  rateLimiting:
    enabled: false
    general:
      rate: "50"
      burst: "150"
    webhook:
      rate: "10"
      burst: "20"
