apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: river-node-wildcard-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: river-node-wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.test-nodes.{{ .Values.global.environmentName }}.towns.com"
    - "*.nodes.{{ .Values.global.environmentName }}.towns.com"
