apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: river-node-wildcard-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: river-node-wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.test-nodes.{{ .Values.global.environmentName }}.towns.com"
    - "*.nodes.{{ .Values.global.environmentName }}.towns.com"

---

{{- range .Values.nodes }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-river-node-test-{{ .nodeType }}-{{ .nodeNumber }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-river-node-test-{{ .nodeType }}-{{ .nodeNumber }}
  template:
    metadata:
      labels:
        app: nginx-river-node-test-{{ .nodeType }}-{{ .nodeNumber }}
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 443
            - containerPort: 80
          volumeMounts:
          - name: certs
            mountPath: "/etc/nginx/certs"
            readOnly: true
          env:
            - name: TLSCONFIG__CERT
              valueFrom:
                secretKeyRef:
                  name: river-node-wildcard-tls
                  key: tls.crt
            - name: TLSCONFIG__KEY
              valueFrom:
                secretKeyRef:
                  name: river-node-wildcard-tls
                  key: tls.key
      volumes:
        - name: certs
          secret:
            secretName: river-node-wildcard-tls

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-river-node-test-{{ .nodeType }}-{{ .nodeNumber }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    cloud.google.com/l4-rbs: enabled
    networking.gke.io/load-balancer-type: "External"
    networking.gke.io/load-balancer-ip-addresses: "river-{{ .nodeType }}-{{ .nodeNumber }}-ip-address"
    external-dns.alpha.kubernetes.io/hostname: "{{ .nodeType }}-{{ .nodeNumber }}.test-nodes.{{ $.Values.global.environmentName }}.towns.com"
spec:
  selector:
    app: nginx-river-node-test-{{ .nodeType }}-{{ .nodeNumber }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
    - protocol: TCP
      port: 80
      targetPort: 80
---

{{- end }}
