apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: river-node-wildcard-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: river-node-wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - "*.test-nodes.{{ .Values.global.environmentName }}.towns.com"
    - "*.nodes.{{ .Values.global.environmentName }}.towns.com"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-river-node-test-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    server {
        listen 443 ssl http2;
        server_name _;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384';
        ssl_prefer_server_ciphers on;
        ssl_session_cache shared:SSL:10m;
        ssl_session_timeout 10m;
        ssl_stapling on;
        ssl_stapling_verify on;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    }

---

{{- range .Values.nodes }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-river-node-test-{{ .nodeType }}-{{ .nodeNumber }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-river-node-test-{{ .nodeType }}-{{ .nodeNumber }}
  template:
    metadata:
      labels:
        app: nginx-river-node-test-{{ .nodeType }}-{{ .nodeNumber }}
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 443
          volumeMounts:
          - name: certs
            mountPath: "/etc/nginx/certs"
            readOnly: true
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          env:
            - name: TLSCONFIG__CERT
              valueFrom:
                secretKeyRef:
                  name: river-node-wildcard-tls
                  key: tls.crt
            - name: TLSCONFIG__KEY
              valueFrom:
                secretKeyRef:
                  name: river-node-wildcard-tls
                  key: tls.key
      volumes:
        - name: certs
          secret:
            secretName: river-node-wildcard-tls
        - name: nginx-config
          configMap:
            name: nginx-argocd-wrapper-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-river-node-test-{{ .nodeType }}-{{ .nodeNumber }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    networking.gke.io/load-balancer-type: "External"
    networking.gke.io/load-balancer-ip-addresses: "river-{{ .nodeType }}-{{ .nodeNumber }}-ip-address"
    external-dns.alpha.kubernetes.io/hostname: "{{ .nodeType }}-{{ .nodeNumber }}.test-nodes.{{ $.Values.global.environmentName }}.towns.com"
spec:
  selector:
    app: nginx-river-node-test-{{ .nodeType }}-{{ .nodeNumber }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---

{{- end }}
