{{- range .Values.nodes }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: river-node-{{ .nodeType }}-{{ .nodeNumber }}-credentials
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: "0" 
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: wallet_private_key
      remoteRef:
        key: river-node-local-credentials
        property: river-{{ .nodeType }}-{{ .nodeNumber }}.wallet_private_key
        version: latest

    - secretKey: base_chain_rpc_url
      remoteRef:
        key: rpc_urls
        property: base
        version: latest

    - secretKey: river_chain_rpc_url
      remoteRef:
        key: rpc_urls
        property: river
        version: latest

    - secretKey: chains_string
      remoteRef:
        key: chains_string
        version: latest

    - secretKey: target_db_host
      remoteRef:
        key: river-node-db-credentials
        property: target_db_host
        version: latest

    - secretKey: target_db_app_user
      value: {{ .dbUser }}

    - secretKey: target_db_app_password
      remoteRef:
        key: river-node-local-credentials
        property: river-{{ .nodeType }}-{{ .nodeNumber }}.database_password
        version: latest

    - secretKey: target_db_root_user
      remoteRef:
        key: river-node-db-credentials
        property: target_db_root_user
        version: latest

    - secretKey: target_db_root_password
      remoteRef:
        key: river-node-db-credentials
        property: target_db_root_password
        version: latest

    - secretKey: source_db_host
      remoteRef:
        key: river-node-db-credentials
        property: source_db_host
        version: latest

    - secretKey: source_db_user
      remoteRef:
        key: river-node-db-credentials
        property: source_db_user
        version: latest

    - secretKey: source_db_password
      remoteRef:
        key: river-node-db-credentials
        property: source_db_password
        version: latest

---

{{- end }}