apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: river-node-db-host
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: river-node-db-host
      remoteRef:
        key: river-node-db-host
        version: latest
