{{- range .Values.nodes }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: river-node-credentials-{{ .nodeType }}-{{ .nodeNumber }}-credentials
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: db_host
      remoteRef:
        key: river-node-db-host
        version: latest
    - secretKey: db_password
      remoteRef:
        key: river-node-local-credentials
        property: river-{{ .nodeType }}-{{ .nodeNumber }}.database_password
        version: latest
    - secretKey: wallet_private_key
      remoteRef:
        key: river-node-local-credentials
        property: river-{{ .nodeType }}-{{ .nodeNumber }}.wallet_private_key
        version: latest
---

{{- end }}