{{- range .Values.nodes }}

apiVersion: v1
kind: Service
metadata:
  name: river-node-{{ .nodeType }}-{{ .nodeNumber }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    cloud.google.com/l4-rbs: "enabled"
    external-dns.alpha.kubernetes.io/hostname: {{ .hostname }}
spec:
  selector:
    app: river-node-{{ .nodeType }}-{{ .nodeNumber }}
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
---

{{- end }}