external-dns:
  provider: cloudflare
  cloudflare:
    secretName: cloudflare-secret
    email: kerem@hntlabs.com
    proxied: false
  policy: sync
  interval: 5m
  logFormat: json
  podAnnotations:
    ad.datadoghq.com/external-dns.logs: '[{"service": "external-dns"}]'
