external-dns:
  provider: cloudflare
  env:
    - name: CF_API_KEY
      valueFrom:
        secretKeyRef:
          name: cloudflare-secret
          key: api_key
    - name: CF_API_EMAIL
      value: kerem@hntlabs.com
