external-dns:
  provider: cloudflare
  cloudflare:
    email: kerem@hntlabs.com
  env:
    - name: CF_API_KEY
      valueFrom:
        secretKeyRef:
          name: cloudflare-secret
          key: api_key
