datadog:
  datadog:
    apiKeyExistingSecret: datadog-secret
    appKeyExistingSecret: datadog-secret

    prometheusScrape:
      enabled: true
      serviceEndpoints: true

    logs:
      enabled: true
      containerCollectAll: false
      autoMultiLineDetection: true

    # otlp:
    #   receiver:
    #     protocols:
    #       grpc:
    #         enabled: true

  agents:
    containers:
      agent:
        # resources for the Agent container
        resources:
          requests:
            cpu: 200m
            memory: 256Mi

      # traceAgent:
      #   # resources for the Trace Agent container
      #   resources:
      #     requests:
      #       cpu: 100m
      #       memory: 200Mi

      # processAgent:
      #   # resources for the Process Agent container
      #   resources:
      #     requests:
      #       cpu: 100m
      #       memory: 200Mi

    priorityClassCreate: true

  clusterAgent:
    enabled: true
    metricsProvider:
      enabled: true
