apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ include "app-registry-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "app-registry-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  healthCheck:
    type: HTTP
    requestPath: /status
    port: 80
    checkIntervalSec: 60
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
