apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-registry-service-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: river-rpc-url
      remoteRef:
        key: rpc_urls
        version: latest
        property: river

    - secretKey: base-rpc-url
      remoteRef:
        key: rpc_urls
        version: latest
        property: base
  
    - secretKey: shared_secret_encryption_key
      remoteRef:
        key: app-registry-service
        property: shared_secret_encryption_key
        version: latest

    - secretKey: session_token_key
      remoteRef:
        key: app-registry-service
        property: session_token_key
        version: latest

    - secretKey: db_host
      remoteRef:
        key: app-registry-service-db-credentials
        property: host
        version: latest

    - secretKey: db_app_password
      remoteRef:
        key: app-registry-service-db-credentials
        property: app_password
        version: latest

    - secretKey: db_app_user
      remoteRef:
        key: app-registry-service-db-credentials
        property: app_user
        version: latest

    - secretKey: db_root_user
      remoteRef:
        key: app-registry-service-db-credentials
        property: root_user
        version: latest

    - secretKey: db_root_password
      remoteRef:
        key: app-registry-service-db-credentials
        property: root_password
        version: latest
