apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-registry-service.fullname" . }}
  labels:
    {{- include "app-registry-service.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "app-registry-service.fullname" . }}" }'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app-registry-service.selectorLabels" . | nindent 4 }}
