---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  labels:
    argocd.argoproj.io/instance: cert-manager
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: { { .Values.letsencrypt.email } }
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
