apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metrics-aggregator.fullname" . }}
  labels:
    {{- include "metrics-aggregator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "metrics-aggregator.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "metrics-aggregator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: prometheus-etc
          emptyDir: {}
      containers:
        - name: metrics-discovery
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.metricsDiscovery.image.repository }}:{{ .Values.metricsDiscovery.image.tag }}"
          imagePullPolicy: {{ .Values.metricsDiscovery.image.pullPolicy }}
          env:
            - name: ENV
              value: {{ .Values.global.environmentName }}
            - name: RIVER_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: metrics-aggregator-secrets
                  key: river-rpc-url
            - name: LOG_PRETTY
              value: "false"
          volumeMounts:
            - name: prometheus-etc
              mountPath: /river/packages/metrics-discovery/prometheus/etc
      