apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "subgraph.fullname" . }}
  labels:
    {{- include "subgraph.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "subgraph.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "subgraph.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "subgraph.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: RIVER_ENV
              value: {{ $.Values.global.environmentName | quote }}
            - name: NODE_ENV
              value: {{ .Values.nodeEnv | quote }}
            - name: PONDER_PORT
              value: {{ .Values.ponderPort | default "42069" | quote }}
            - name: PONDER_ENVIRONMENT
              value: {{ $.Values.global.environmentName | quote }}
            - name: PONDER_START_BLOCK
              value: {{ required "ponderStartBlock is required" $.Values.ponderStartBlock | quote }}
            - name: PONDER_LOG_LEVEL
              value: {{ $.Values.ponderLogLevel | default "info" | quote }}
            - name: PONDER_CONFIG
              value: "ponder.config.{{ $.Values.global.environmentName | default "gamma" }}.ts"
            - name: PONDER_RPC_URL_1
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name | default "subgraph-secrets" }}
                  key: base_chain_rpc_url
            - name: DATABASE_SCHEMA
              value: "{{ $.Values.global.environmentName }}-{{ .Values.image.tag | default .Chart.AppVersion }}"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name | default "subgraph-secrets" }}
                  key: db_host 
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name | default "subgraph-secrets" }}
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name | default "subgraph-secrets" }}
                  key: db_password
            {{- if .Values.additionalEnv }}
            {{- toYaml .Values.additionalEnv | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: cache-volume
              mountPath: /home/node/.cache
            - name: node-volume
              mountPath: /home/node
            - name: tmp-volume
              mountPath: /tmp
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: node-volume
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }} 