apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: subgraph-secrets
  labels: {{- include "subgraph.labels" . | nindent 4 }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: base_chain_rpc_url
      remoteRef:
        key: subgraph_rpc_urls
        property: base
        version: latest

    - secretKey: db_host
      remoteRef:
        key: subgraph-db-credentials
        property: db_host
        version: latest

    - secretKey: db_user
      remoteRef:
        key: subgraph-db-credentials
        property: root_user
        version: latest

    - secretKey: db_password
      remoteRef:
        key: subgraph-db-credentials
        property: root_password
        version: latest

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: subgraph-secondary-secrets
  labels: {{- include "subgraph.labels" . | nindent 4 }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: base_chain_rpc_url
      remoteRef:
        key: subgraph_rpc_urls
        property: base
        version: latest

    - secretKey: db_host
      remoteRef:
        key: subgraph-db-secondary-credentials
        property: db_host
        version: latest

    - secretKey: db_user
      remoteRef:
        key: subgraph-db-secondary-credentials
        property: root_user
        version: latest

    - secretKey: db_password
      remoteRef:
        key: subgraph-db-secondary-credentials
        property: root_password
        version: latest
