apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-alpha # TODO: always update
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:HereNotThere/argocd.git
    targetRevision: main
    path: charts/app-of-apps
    helm:
      valueFiles:
        - ../../environments/alpha/rendered/global.yaml
        - ../../environments/alpha/rendered/app-of-apps.yaml
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
