# ################### GLOBAL ###################

global:
  environmentName: alpha

chains:
  river:
    chainId: "6524490"
    contractAddresses:
      riverRegistry: "0x44354786EacBEBf981453A05728E1653Bc3c5def"
  base:
    chainId: "84532"
    contractAddresses:
      spaceArchitect: "0xC09Ac0FFeecAaE5100158247512DC177AeacA3e3"
      baseRegistry: "0x0230a9d28bc48a90d6f5e5112b24319ec1b14c52"

notificationService:
  image:
    tag: "ab65192"
  resources:
    requests:
      cpu: 1000m
      memory: 7.5Gi
    limits:
      cpu: 1000m
      memory: 7.5Gi
  apnsTownsAppIdentifier: com.towns.ios.alpha

riverNode:
  image:
    tag: "8c9cbec"
  useRpcGateway: true
  riverRegistryPageSize: 1500
  numStreamNodes: 10
  numArchiveNodes: 0
  race: true
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2.5Gi

appRegistryService:
  image:
    tag: "fc753cf"
  resources:
    requests:
      cpu: 0.5
      memory: 1.5Gi
    limits:
      cpu: 1
      memory: 2Gi

subgraph:
  image:
    tag: "25572ed"
  environment: gamma
  ponderPort: 80
  ponderStartBlock: "22890725"
  ponderLogLevel: "debug"
  nodeEnv: "development"
  secrets:
    name:
  resources:
    requests:
      cpu: 0.5
      memory: 1.5Gi
    limits:
      cpu: 1
      memory: 2Gi

argocd:
  externalAccess:
    enabled: true

rpcGateway:
  image:
    tag: "latest"

xchainMonitor:
  image:
    tag: "latest"
  resources:
    limits:
      cpu: 1
      memory: 5Gi
    requests:
      cpu: 0.4
      memory: 4Gi

metricsAggregator:
  prometheus:
    resources:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 0.5
        memory: 1Gi
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1Gi

appOfApps:
  applications:
  - name: argocd
    namespace: argocd
    disable: false
  - name: datadog
    namespace: datadog
    disable: false
  - name: external-secrets
    namespace: external-secrets
    disable: false
  - name: cert-manager
    namespace: cert-manager
    disable: false
  - name: external-dns
    namespace: external-dns
    disable: false
  - name: main-alb
    namespace: default
    disable: false
  - name: xchain-monitor
    namespace: default
    disable: true
  - name: metrics-aggregator
    namespace: default
    disable: false
  - name: notification-service
    namespace: default
    disable: false
  - name: river-node
    namespace: default
    disable: false
  - name: rpc-gateway
    namespace: default
    disable: false
  - name: subgraph
    namespace: default
    disable: true
  - name: app-registry-service
    namespace: default
    disable: false
