apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: river-notification-service-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: river-notification-service-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - {{ include "notification-service.domainName" . }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "main-alb-ip"
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "true"
spec:
  tls:
    - hosts:
        - {{ include "notification-service.domainName" . }}
      secretName: river-notification-service-tls
  rules:
    - host: {{ include "notification-service.domainName" . }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ include "notification-service.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}

