apiVersion: batch/v1
kind: Job
metadata:
  name: notification-service-init-job
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: notification-service-init-job
    spec:
      restartPolicy: Never
      containers:
        - name: notification-service-init-job
          image: node:20 # Node.js with TypeScript installed
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt-get update && apt-get install -y postgresql-client &&
              git clone --depth=1 https://github.com/HereNotThere/argocd /app &&
              cd /app/scripts/notification-service-db-config &&
              bash ./run.sh
          env:
            - name: TARGET_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: target_db_host

            - name: TARGET_DB_DATABASE
              value: river

            - name: TARGET_DB_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: target_db_root_user

            - name: TARGET_DB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: target_db_root_password

            - name: TARGET_DB_APP_USER
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: target_db_app_user

            - name: TARGET_DB_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: target_db_app_password

            - name: SOURCE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: source_db_host

            - name: SOURCE_DB_DATABASE
              value: river

            - name: SOURCE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: source_db_user

            - name: SOURCE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-service-secrets
                  key: source_db_password
