apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: notification-service-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: river-rpc-url
      remoteRef:
        key: rpc_urls
        version: latest
        property: river

    - secretKey: session_token_key
      remoteRef:
        key: notification-service
        property: session_token_key
        version: latest

    - secretKey: apns_auth_key
      remoteRef:
        key: notification-service
        property: apns_auth_key
        version: latest

    - secretKey: webpush_vapid_public_key
      remoteRef:
        key: notification-service
        property: webpush_vapid_public_key
        version: latest

    - secretKey: webpush_vapid_private_key
      remoteRef:
        key: notification-service
        property: webpush_vapid_private_key
        version: latest

    - secretKey: target_db_host
      remoteRef:
        key: notification-service-db-credentials
        property: target_db_host
        version: latest

    - secretKey: target_db_app_password
      remoteRef:
        key: notification-service-db-credentials
        property: target_db_app_password
        version: latest

    - secretKey: target_db_app_user
      remoteRef:
        key: notification-service-db-credentials
        property: target_db_app_user
        version: latest

    - secretKey: target_db_root_user
      remoteRef:
        key: notification-service-db-credentials
        property: target_db_root_user
        version: latest

    - secretKey: target_db_root_password
      remoteRef:
        key: notification-service-db-credentials
        property: target_db_root_password
        version: latest
