argo-cd:
  server:
    podAnnotations:
      ad.datadoghq.com/server.logs: '[{"source": "argocd", "service": "argocd-server"}]'
      ad.datadoghq.com/server.checks: |
        {
          "argocd": {
            "init_config": {},
            "instances": [
              {
                "api_server_endpoint": "http://%%host%%:8083/metrics"
              }
            ]
          }
        }

  repoServer:
    podAnnotations:
      ad.datadoghq.com/argocd-repo-server.logs: '[{"source": "argocd", "service": "argocd-repo-server"}]'
      ad.datadoghq.com/repo-server.checks: |
        {
          "argocd": {
            "init_config": {},
            "instances": [
              {
                "repo_server_endpoint": "http://%%host%%:8084/metrics"
              }
            ]
          }
        }

  controller:
    podAnnotations:
      ad.datadoghq.com/argocd-application-controller.logs: '[{"source": "argocd", "service": "argocd-application-controller"}]'
      ad.datadoghq.com/application-controller.checks: |
        {
          "argocd": {
            "init_config": {},
            "instances": [
              {
                "app_controller_endpoint": "http://%%host%%:8082/metrics"
              }
            ]
          }
        }
