apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-argocd-wrapper-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      # Rate limits per IP
      limit_req_zone $binary_remote_addr zone=general:2m rate=10r/s;
      limit_req_zone $binary_remote_addr zone=webhook:2m rate=5r/s;
      limit_req_status 429;

      server {
        listen 80;

        limit_req zone=general burst=30;

        client_max_body_size 50M;

        # Common proxy settings
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;

        location /swagger-ui/ {
          return 403;
        }

        location /swagger.json {
          return 403;
        }

        location /api/webhook/ {
          # Stricter rate limit for webhooks
          limit_req zone=webhook burst=10;

          # Smaller body size for webhook
          client_max_body_size 2m;

          proxy_pass http://argocd-server.argocd.svc.cluster.local:80;
        }

        location / {
          proxy_pass http://argocd-server.argocd.svc.cluster.local:80;
        }
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argocd-wrapper
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-argocd-wrapper
  template:
    metadata:
      labels:
        app: nginx-argocd-wrapper
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-argocd-wrapper-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-argocd-wrapper
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: nginx-argocd-wrapper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
