apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-argocd-wrapper-config
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        location / {
          proxy_pass http://argocd-server.argocd.svc.cluster.local:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-argocd-wrapper
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-argocd-wrapper
  template:
    metadata:
      labels:
        app: nginx-argocd-wrapper
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-argocd-wrapper-config

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-argocd-wrapper
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: nginx-argocd-wrapper
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
