### MAIN CERT ###

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: main-alb-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: main-alb-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    {{- if not .Values.notificationService.disable }}
    - {{ include "notification-service.domainName" . }}
    {{- end }}
    - {{ include "argocd.domainName" . }}
    {{- if not .Values.subgraph.disable }}
    - {{ include "subgraph.domainName" . }}
    {{- end }}
    {{- if not .Values.rpcGateway.disable }}
    - {{ include "rpc-gateway.domainName" . }}
    {{- end }}
    {{- if not .Values.appRegistryService.disable }}
    - {{ include "app-registry-service.domainName" . }}
    {{- end }}
    {{- if not .Values.notificationSendit.disable }}
    - {{ include "notification-sendit.domainName" . }}
    {{- end }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "main-alb.fullname" . }}
  labels: {{- include "main-alb.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "main-alb-ip"
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "false"
    external-dns.alpha.kubernetes.io/hostname: {{ include "main-alb.hosts" . }}
spec:
  tls:
    - hosts:
        {{- if not .Values.notificationService.disable }}
        - {{ include "notification-service.domainName" . }}
        {{- end }}
        - {{ include "argocd.domainName" . }}
        {{- if not .Values.subgraph.disable }}
        - {{ include "subgraph.domainName" . }}
        {{- end }}
        {{- if not .Values.rpcGateway.disable }}
        - {{ include "rpc-gateway.domainName" . }}
        {{- end }}
        {{- if not .Values.appRegistryService.disable }}
        - {{ include "app-registry-service.domainName" . }}
        {{- end }}
        {{- if not .Values.notificationSendit.disable }}
        - {{ include "notification-sendit.domainName" . }}
        {{- end }}
      secretName: main-alb-tls
  rules:
    {{- if not .Values.notificationService.disable }}
    - host: {{ include "notification-service.domainName" . }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 80
    {{- end }}
    {{- if not .Values.appRegistryService.disable }}
    - host: {{ include "app-registry-service.domainName" . }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: app-registry-service
                port:
                  number: 80
    {{- end }}
    - host: {{ include "argocd.domainName" . }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: nginx-argocd-wrapper
                port:
                  number: 80
    {{- if not .Values.subgraph.disable }}
    - host: {{ include "subgraph.domainName" . }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: subgraph
                port:
                  number: 80
    {{- end }}
    {{- if not .Values.rpcGateway.disable }}
    - host: {{ include "rpc-gateway.domainName" . }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: rpc-gateway
                port:
                  number: 8080
    {{- end }}
    {{- if not .Values.notificationSendit.disable }}
    - host: {{ include "notification-sendit.domainName" . }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: notification-sendit
                port:
                  number: 80
    {{- end }}

---
### MAIN SERVICE ACCOUNT ###
apiVersion: v1
kind: ServiceAccount
metadata:
  name: main-service-account
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: main-service-account@{{ .Values.global.gcp.projectId }}.iam.gserviceaccount.com
