name: Update Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        type: choice
        required: true
        default: "gamma"
        options:
          - "gamma"
          - "alpha"
          - "omega"
          - "delta"
      notificationServiceImageTag:
        description: "notificationService.image.tag"
        type: string
        required: false
  repository_dispatch:
    types: [custom-event]

jobs:
  update_infra:
    permissions: write-all
    runs-on: "ubuntu-latest"
    timeout-minutes: 5

    concurrency:
      group: ci-${{ github.event.inputs.environment || github.event.client_payload.environment }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Install node dependencies
        run: yarn install

      - name: Determine values to update
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "Workflow dispatch event detected"
            ENV="${{ github.event.inputs.environment }}"
            NOTIFICATION_SERVICE_IMAGE_TAG="${{ github.event.inputs.notificationServiceImageTag }}"

          elif [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "Repository dispatch event detected"
            ENV="${{ github.event.client_payload.environment }}"
            NOTIFICATION_SERVICE_IMAGE_TAG="${{ github.event.client_payload.notificationServiceImageTag }}"

          else
            echo "Unknown event type: ${{ github.event_name }}, exiting"
            exit 1
          fi

          if [[ -z "$ENV" ]]; then
            echo "Environment not set, exiting"
            exit 1
          else
            echo "Environment set to $ENV"
          fi

          VALUES=""

          # if the notification service tag is set
          if [[ -n "$NOTIFICATION_SERVICE_IMAGE_TAG" ]]; then
            VALUES="notificationService.image.tag=$NOTIFICATION_SERVICE_IMAGE_TAG"
          fi

          echo "VALUES=${VALUES}" >> $GITHUB_ENV
          echo "ENV=${ENV}" >> $GITHUB_ENV

      - name: Update values
        env:
          ENV: ${{ env.ENV }}
          VALUES: ${{ env.VALUES }}
        run: ENV=${ENV} VALUES=${VALUES} make set_values

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          # Check if there are any changes
          if git diff --cached --exit-code; then
            echo "No changes to commit."
            exit 0
          fi

          # Get the date and time
          DATE=$(date)

          git commit -m "Auto-update values: $ENV - $DATE"
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
